### ISSUE TITLE
Create Appropriate headings for separation of content in the README

### ISSUE THREAD

**Issue by mihirk284** [Aerodynamics-Club/awesome-resources#2]
Please create appropriate headings and subheadings for content arrangement in the README. Once this is set up correctly, everyone will be able to contribute to the doc.

**Comment by hardesh** [comment]
Also, while adding new resources I think a proper citation style can be followed.

**Comment by Matnay** [comment]
> Also, while adding new resources I think a proper citation style can be followed.

I had added an initial entry under each subsection to ensure that the contributors are aware that the same citation style is to be followed. If you feel there should be any changes to said style please let us know.
Apart from this we can add a file that explicitly mentions these guidelines if all the maintainers agree

**Comment by hardesh** [comment]
Checkout the projects section from [this](https://github.com/tzutalin/awesome-visual-slam) awesome list

**Comment by Matnay** [comment]
I saw this but thought it was quite verbose. Instead just thought of adding a link to where the paper can be found and if there is an open-source implementation available, then a link to that too. Should we shift to that style as it does seem like a more correct way of citing the work though?

**Comment by hardesh** [comment]
> Should we shift to that style as it does seem like a more correct way of citing the work though?

Yeah, I think you should
